version: '3.9'

services:
  frontend:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development